baseURL = 'https://theroundtablecontinues.com/'
languageCode = 'en-us'
DefaultContentLanguage = 'en-us'
title = 'The Roundtable Continues'
theme = 'anatole'  # theme as git submodule
publishDir = 'docs'

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
